In [ ]:
导入并查看numpy版本

In [22]:
import numpy as np
print(np.__version__)

1.21.5


In [ ]:
创建10个全为0的一维数据并修改数据类型为整数

In [14]:
import numpy as np
from numpy import array
np.zeros(10,dtype = 'int')
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
创建20个0-100固定步长的数

In [16]:
import numpy as np
from numpy import array
np.arange(0,100,5)
array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
实现创建⼀个10*10的ndarray对象，满⾜矩阵边界全为1，⾥⾯全为0

In [17]:
import numpy as np
obj = np.zeros((10, 10))
obj[0, :] = obj[9, :] = obj[:, 0] = obj[:, 9] = 1
print(obj)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
使用numpy生成6行6列的二维数组，值为1-100随机数，找到每列的最大值，获取data每行元素的大小排名，将数组按行重复一次，去除数组的重复行

In [20]:
import numpy as np
data = np.random.randint(1,100,[6,6])
np.amax(data,axis=0)
np.unique(data,return_counts=True)
data.argsort()
np.repeat(data,2,axis=0)
np.unique(data,axis=0)

array([[11, 60, 19, 52, 45,  6],
       [12, 93, 15, 66, 16, 46],
       [49, 63, 15, 12, 78, 55],
       [64, 94, 13, 89, 81, 25],
       [92, 72, 53, 51, 21, 11],
       [94, 53, 10, 15, 90, 69]])